package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Case implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.introduction
	 * @mbggenerated
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.main_img
	 * @mbggenerated
	 */
	private String main_img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.case_img
	 * @mbggenerated
	 */
	private String case_img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.url_open_type
	 * @mbggenerated
	 */
	private Integer url_open_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_case.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_case
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.id
	 * @return  the value of t_case.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.id
	 * @param id  the value for t_case.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.name
	 * @return  the value of t_case.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.name
	 * @param name  the value for t_case.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.introduction
	 * @return  the value of t_case.introduction
	 * @mbggenerated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.introduction
	 * @param introduction  the value for t_case.introduction
	 * @mbggenerated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.type
	 * @return  the value of t_case.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.type
	 * @param type  the value for t_case.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.status
	 * @return  the value of t_case.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.status
	 * @param status  the value for t_case.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.main_img
	 * @return  the value of t_case.main_img
	 * @mbggenerated
	 */
	public String getMain_img() {
		return main_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.main_img
	 * @param main_img  the value for t_case.main_img
	 * @mbggenerated
	 */
	public void setMain_img(String main_img) {
		this.main_img = main_img == null ? null : main_img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.case_img
	 * @return  the value of t_case.case_img
	 * @mbggenerated
	 */
	public String getCase_img() {
		return case_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.case_img
	 * @param case_img  the value for t_case.case_img
	 * @mbggenerated
	 */
	public void setCase_img(String case_img) {
		this.case_img = case_img == null ? null : case_img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.url_open_type
	 * @return  the value of t_case.url_open_type
	 * @mbggenerated
	 */
	public Integer getUrl_open_type() {
		return url_open_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.url_open_type
	 * @param url_open_type  the value for t_case.url_open_type
	 * @mbggenerated
	 */
	public void setUrl_open_type(Integer url_open_type) {
		this.url_open_type = url_open_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.url
	 * @return  the value of t_case.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.url
	 * @param url  the value for t_case.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_case.time
	 * @return  the value of t_case.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_case.time
	 * @param time  the value for t_case.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_case
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Case other = (Case) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getIntroduction() == null ? other.getIntroduction() == null
						: this.getIntroduction().equals(other.getIntroduction()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getMain_img() == null ? other.getMain_img() == null
						: this.getMain_img().equals(other.getMain_img()))
				&& (this.getCase_img() == null ? other.getCase_img() == null
						: this.getCase_img().equals(other.getCase_img()))
				&& (this.getUrl_open_type() == null ? other.getUrl_open_type() == null
						: this.getUrl_open_type().equals(other.getUrl_open_type()))
				&& (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_case
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getMain_img() == null) ? 0 : getMain_img().hashCode());
		result = prime * result + ((getCase_img() == null) ? 0 : getCase_img().hashCode());
		result = prime * result + ((getUrl_open_type() == null) ? 0 : getUrl_open_type().hashCode());
		result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_case
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", introduction=").append(introduction);
		sb.append(", type=").append(type);
		sb.append(", status=").append(status);
		sb.append(", main_img=").append(main_img);
		sb.append(", case_img=").append(case_img);
		sb.append(", url_open_type=").append(url_open_type);
		sb.append(", url=").append(url);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}