package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class Group implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.station
	 * @mbggenerated
	 */
	private String station;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.home_page
	 * @mbggenerated
	 */
	private Integer home_page;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.introduction
	 * @mbggenerated
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.main_img
	 * @mbggenerated
	 */
	private String main_img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.group_img
	 * @mbggenerated
	 */
	private String group_img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_group.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_group
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.id
	 * @return  the value of t_group.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.id
	 * @param id  the value for t_group.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.name
	 * @return  the value of t_group.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.name
	 * @param name  the value for t_group.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.station
	 * @return  the value of t_group.station
	 * @mbggenerated
	 */
	public String getStation() {
		return station;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.station
	 * @param station  the value for t_group.station
	 * @mbggenerated
	 */
	public void setStation(String station) {
		this.station = station == null ? null : station.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.home_page
	 * @return  the value of t_group.home_page
	 * @mbggenerated
	 */
	public Integer getHome_page() {
		return home_page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.home_page
	 * @param home_page  the value for t_group.home_page
	 * @mbggenerated
	 */
	public void setHome_page(Integer home_page) {
		this.home_page = home_page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.email
	 * @return  the value of t_group.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.email
	 * @param email  the value for t_group.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.status
	 * @return  the value of t_group.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.status
	 * @param status  the value for t_group.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.introduction
	 * @return  the value of t_group.introduction
	 * @mbggenerated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.introduction
	 * @param introduction  the value for t_group.introduction
	 * @mbggenerated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.main_img
	 * @return  the value of t_group.main_img
	 * @mbggenerated
	 */
	public String getMain_img() {
		return main_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.main_img
	 * @param main_img  the value for t_group.main_img
	 * @mbggenerated
	 */
	public void setMain_img(String main_img) {
		this.main_img = main_img == null ? null : main_img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.group_img
	 * @return  the value of t_group.group_img
	 * @mbggenerated
	 */
	public String getGroup_img() {
		return group_img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.group_img
	 * @param group_img  the value for t_group.group_img
	 * @mbggenerated
	 */
	public void setGroup_img(String group_img) {
		this.group_img = group_img == null ? null : group_img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_group.time
	 * @return  the value of t_group.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_group.time
	 * @param time  the value for t_group.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Group other = (Group) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getStation() == null ? other.getStation() == null
						: this.getStation().equals(other.getStation()))
				&& (this.getHome_page() == null ? other.getHome_page() == null
						: this.getHome_page().equals(other.getHome_page()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getIntroduction() == null ? other.getIntroduction() == null
						: this.getIntroduction().equals(other.getIntroduction()))
				&& (this.getMain_img() == null ? other.getMain_img() == null
						: this.getMain_img().equals(other.getMain_img()))
				&& (this.getGroup_img() == null ? other.getGroup_img() == null
						: this.getGroup_img().equals(other.getGroup_img()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getStation() == null) ? 0 : getStation().hashCode());
		result = prime * result + ((getHome_page() == null) ? 0 : getHome_page().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
		result = prime * result + ((getMain_img() == null) ? 0 : getMain_img().hashCode());
		result = prime * result + ((getGroup_img() == null) ? 0 : getGroup_img().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", station=").append(station);
		sb.append(", home_page=").append(home_page);
		sb.append(", email=").append(email);
		sb.append(", status=").append(status);
		sb.append(", introduction=").append(introduction);
		sb.append(", main_img=").append(main_img);
		sb.append(", group_img=").append(group_img);
		sb.append(", time=").append(time);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}