package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.type
	 * @mbggenerated
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.key_words
	 * @mbggenerated
	 */
	private String key_words;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.img_one
	 * @mbggenerated
	 */
	private String img_one;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.img_two
	 * @mbggenerated
	 */
	private String img_two;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.img_three
	 * @mbggenerated
	 */
	private String img_three;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.source
	 * @mbggenerated
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.time
	 * @mbggenerated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_news.content
	 * @mbggenerated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_news
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.id
	 * @return  the value of t_news.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.id
	 * @param id  the value for t_news.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.type
	 * @return  the value of t_news.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.type
	 * @param type  the value for t_news.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.title
	 * @return  the value of t_news.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.title
	 * @param title  the value for t_news.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.key_words
	 * @return  the value of t_news.key_words
	 * @mbggenerated
	 */
	public String getKey_words() {
		return key_words;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.key_words
	 * @param key_words  the value for t_news.key_words
	 * @mbggenerated
	 */
	public void setKey_words(String key_words) {
		this.key_words = key_words == null ? null : key_words.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.img_one
	 * @return  the value of t_news.img_one
	 * @mbggenerated
	 */
	public String getImg_one() {
		return img_one;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.img_one
	 * @param img_one  the value for t_news.img_one
	 * @mbggenerated
	 */
	public void setImg_one(String img_one) {
		this.img_one = img_one == null ? null : img_one.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.img_two
	 * @return  the value of t_news.img_two
	 * @mbggenerated
	 */
	public String getImg_two() {
		return img_two;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.img_two
	 * @param img_two  the value for t_news.img_two
	 * @mbggenerated
	 */
	public void setImg_two(String img_two) {
		this.img_two = img_two == null ? null : img_two.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.img_three
	 * @return  the value of t_news.img_three
	 * @mbggenerated
	 */
	public String getImg_three() {
		return img_three;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.img_three
	 * @param img_three  the value for t_news.img_three
	 * @mbggenerated
	 */
	public void setImg_three(String img_three) {
		this.img_three = img_three == null ? null : img_three.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.source
	 * @return  the value of t_news.source
	 * @mbggenerated
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.source
	 * @param source  the value for t_news.source
	 * @mbggenerated
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.status
	 * @return  the value of t_news.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.status
	 * @param status  the value for t_news.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.time
	 * @return  the value of t_news.time
	 * @mbggenerated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.time
	 * @param time  the value for t_news.time
	 * @mbggenerated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_news.content
	 * @return  the value of t_news.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_news.content
	 * @param content  the value for t_news.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		News other = (News) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getKey_words() == null ? other.getKey_words() == null
						: this.getKey_words().equals(other.getKey_words()))
				&& (this.getImg_one() == null ? other.getImg_one() == null
						: this.getImg_one().equals(other.getImg_one()))
				&& (this.getImg_two() == null ? other.getImg_two() == null
						: this.getImg_two().equals(other.getImg_two()))
				&& (this.getImg_three() == null ? other.getImg_three() == null
						: this.getImg_three().equals(other.getImg_three()))
				&& (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
				&& (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getKey_words() == null) ? 0 : getKey_words().hashCode());
		result = prime * result + ((getImg_one() == null) ? 0 : getImg_one().hashCode());
		result = prime * result + ((getImg_two() == null) ? 0 : getImg_two().hashCode());
		result = prime * result + ((getImg_three() == null) ? 0 : getImg_three().hashCode());
		result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
		result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", type=").append(type);
		sb.append(", title=").append(title);
		sb.append(", key_words=").append(key_words);
		sb.append(", img_one=").append(img_one);
		sb.append(", img_two=").append(img_two);
		sb.append(", img_three=").append(img_three);
		sb.append(", source=").append(source);
		sb.append(", status=").append(status);
		sb.append(", time=").append(time);
		sb.append(", content=").append(content);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}