package com.yqwl.pojo;

import java.io.Serializable;
import java.util.Date;

public class NewsImg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_img.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_img.news_id
     *
     * @mbggenerated
     */
    private Long news_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_img.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_img.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_img.id
     *
     * @return the value of t_news_img.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_img.id
     *
     * @param id the value for t_news_img.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_img.news_id
     *
     * @return the value of t_news_img.news_id
     *
     * @mbggenerated
     */
    public Long getNews_id() {
        return news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_img.news_id
     *
     * @param news_id the value for t_news_img.news_id
     *
     * @mbggenerated
     */
    public void setNews_id(Long news_id) {
        this.news_id = news_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_img.url
     *
     * @return the value of t_news_img.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_img.url
     *
     * @param url the value for t_news_img.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_img.time
     *
     * @return the value of t_news_img.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_img.time
     *
     * @param time the value for t_news_img.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NewsImg other = (NewsImg) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNews_id() == null ? other.getNews_id() == null : this.getNews_id().equals(other.getNews_id()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNews_id() == null) ? 0 : getNews_id().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", news_id=").append(news_id);
        sb.append(", url=").append(url);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}