package com.yqwl.dao;

import java.util.List;

import com.yqwl.pojo.Amount;

public interface AmountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	int insert(Amount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	int insertSelective(Amount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	Amount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Amount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_amount
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Amount record);

	int total();

	List<Amount> listByNow();

	List<Amount> listBy7day();

	List<Amount> listBy30day();
}