package com.yqwl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.pojo.Group;
import com.yqwl.pojo.Message;

public interface MessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	Message selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Message record);
	/**
	 * 
	 * @Title: listAll
	 * @description: 分页查询所有留言
	 *
	 * @param beginPageIndex
	 * @param limit
	 * @return    
	 * @return List<Message>   
	 *
	 * @author HanMeng
	 * @createDate 2019年2月18日-上午10:12:32
	 */
	List<Message> listAll(@Param("beginPageIndex")Integer beginPageIndex,@Param("limit")Integer limit);
	/**
	 * 
	 * @Title: listAllCount
	 * @description: 查询留言总数
	 *
	 * @return    
	 * @return int   
	 *
	 * @author HanMeng
	 * @createDate 2019年2月18日-上午10:12:53
	 */
	int listAllCount();

	Integer total();
}