package com.yqwl.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yqwl.pojo.Case;
import com.yqwl.pojo.News;

public interface NewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int insert(News record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int insertSelective(News record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	News selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(News record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(News record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_news
	 * @mbggenerated
	 */
	int updateByPrimaryKey(News record);
	List<News> listAll(@Param("beginPageIndex")Integer beginPageIndex,@Param("limit")Integer limit);
	int listAllCount();
	/**
	 * 
	     * @Title: 
	     * @description 获得企业动态
	     * @param  栏目
	     * @return    
	     * @author chenshuxian
	     * @createDate 2019年4月1日
	 */
	List<News> getBusinessMovement(@Param("type")String type,@Param("beginPageIndex")Integer beginPageIndex,@Param("limit")Integer limit);
	/**
	 * 
	     * @Title: 
	     * @description 获得企业数量
	     * @param  
	     * @return    
	     * @author chenshuxian
	     * @createDate 2019年4月1日
	 */
	Integer getNewsCount();
}