package com.yqwl.dao;

import java.util.List;
import com.yqwl.pojo.NewsImg;

public interface NewsImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    int insert(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    int insertSelective(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    NewsImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsImg record);
    
    
    List<NewsImg> getByNewsId(Long id);
}